# Generated by Django 5.1.1 on 2025-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('yes', 'Yes'), ('no', 'No')], default='none', max_length=10),
        ),
    ]
